### ISSUE TITLE
Rename git primary branch to "main"

### ISSUE THREAD

**Issue by kaworu** [cilium/hubble#1027]
See https://github.com/cilium/cilium/issues/23110
```[tasklist]
### Tasks
- [x] Announce the change on Slack
- [ ] Change the GitHub setting to rename the `master` branch to `main`
- [ ] merge https://github.com/cilium/hubble/pull/1147
- [ ] check that every open PR is now targeting the `main` branch instead of `master`
```

**Comment by kaworu** [comment]
The switch is planned for July 24th and has been announced on Cilium's Slack `#sig-hubble` channel.
